
customizations:
  cloudFormationStackSets:  
    # This is a comment for the below component
    - name: S3Bucket
      description: s3bucket
      regions:
        - us-east-1
      deploymentTargets:
        accounts:
          - Shared-Services
      template: COMPONENT_PATH_PLACEHOLDER/bucket.yaml
      parameters:
        - name: BucketName
          value: this-is-a-unique-bucket-name-foo-sf
